#!/bin/sh
# Generate a self-service guest WiFi info page served by the router's built-in web server.
#
# Usage: sh guest-info.sh <config-file>
#
# Creates /www/net/<iface>.html — accessible from LAN at:
#   http://<router-ip>/net/<iface>.html
#
# Guest and untrusted zones cannot reach the router's web server (INPUT=REJECT),
# so this page is LAN-only by default.

set -eu

[ $# -eq 1 ] || { echo "Usage: sh guest-info.sh <config-file>"; exit 1; }

CONFIG="$1"
[ -f "$CONFIG" ] || { echo "ERROR: config not found: $CONFIG"; exit 1; }
. "$CONFIG"

[ -z "${IFACE:-}" ] && { echo "ERROR: IFACE not set"; exit 1; }
[ -z "${SSID:-}"  ] && { echo "ERROR: SSID not set";  exit 1; }

WIFI_KEY="${WIFI_KEY:-}"

if [ -z "$WIFI_KEY" ]; then
    # Try to read from UCI (on router)
    WIFI_UCI="${WIFI_UCI:-$IFACE}"
    WIFI_KEY=$(uci -q get wireless."$WIFI_UCI".key 2>/dev/null || true)
    [ -z "$WIFI_KEY" ] && { echo "ERROR: WIFI_KEY not set and not found in UCI"; exit 1; }
fi

# Map encryption to WPA type for QR code
case "${ENCRYPTION:-}" in
    sae*)       QR_TYPE=SAE ;;
    psk*|wpa*)  QR_TYPE=WPA ;;
    none|open)  QR_TYPE=nopass ;;
    *)          QR_TYPE=WPA ;;
esac

QR_STRING="WIFI:T:${QR_TYPE};S:${SSID};P:${WIFI_KEY};;"

# Generate QR code as SVG if qrencode available
QR_BLOCK=""
if command -v qrencode >/dev/null 2>&1; then
    QR_SVG=$(qrencode -t SVG -m 2 -o - "$QR_STRING" 2>/dev/null || true)
    if [ -n "$QR_SVG" ]; then
        QR_BLOCK="<div class=\"qr\">$QR_SVG</div>"
    fi
fi

mkdir -p /www/net

cat >/www/net/${IFACE}.html <<HTML
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>WiFi — ${SSID}</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 480px; margin: 4rem auto; padding: 1rem; color: #111; }
  h1 { font-size: 1.4rem; margin-bottom: 0.25rem; }
  .sub { color: #666; font-size: 0.9rem; margin-bottom: 2rem; }
  .card { background: #f5f5f5; border-radius: 12px; padding: 1.5rem; margin-bottom: 1.5rem; }
  .label { font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em; color: #888; margin-bottom: 0.25rem; }
  .value { font-size: 1.2rem; font-weight: 600; word-break: break-all; }
  .qr { margin: 1.5rem 0; text-align: center; }
  .qr svg { max-width: 220px; height: auto; border-radius: 8px; }
  .enc { display: inline-block; background: #e8f5e9; color: #2e7d32; font-size: 0.75rem; padding: 0.15rem 0.5rem; border-radius: 4px; margin-top: 0.5rem; }
  footer { font-size: 0.75rem; color: #aaa; margin-top: 2rem; }
</style>
</head>
<body>
<h1>${SSID}</h1>
<p class="sub">Scan the QR code or enter the password manually.</p>

${QR_BLOCK}

<div class="card">
  <div class="label">Network name (SSID)</div>
  <div class="value">${SSID}</div>
</div>

<div class="card">
  <div class="label">Password</div>
  <div class="value">${WIFI_KEY}</div>
  <span class="enc">${QR_TYPE}</span>
</div>

<footer>Generated by openwrt-extra-networks &middot; $(date '+%Y-%m-%d %H:%M')</footer>
</body>
</html>
HTML

ROUTER_IP=$(ip addr show br-lan 2>/dev/null | awk '/inet / { split($2,a,"/"); print a[1]; exit }')
ROUTER_IP="${ROUTER_IP:-192.168.1.1}"

echo "Generated: /www/net/${IFACE}.html"
echo "Access at: http://${ROUTER_IP}/net/${IFACE}.html  (LAN only)"
